export const SHOW_LOGIN_FORM = 'SHOW_LOGIN_FORM';
export const CLOSE_LOGIN_FORM = 'CLOSE_LOGIN_FORM';

export const LOG_IN_REQUEST = 'LOG_IN_REQUEST';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';
export const LOG_OUT = 'LOG_OUT';

export const PIZZA_EDIT = 'PIZZA_EDIT';
export const PIZZA_CHANGE_SIZE = 'PIZZA_CHANGE_SIZE';
export const PIZZA_CHANGE_INGREDIENTS = 'PIZZA_CHANGE_INGREDIENTS';
export const ADD_NEW_PIZZA = 'ADD_NEW_PIZZA';

export const PIZZA_DELETE_LOCALLY = 'PIZZA_DELETE_LOCALLY';
// export const PIZZA_DELETE_REMOTELY = 'PIZZA_DELETE_REMOTELY';

export const PIZZA_UPDATE_LOCALLY = 'PIZZA_UPDATE_LOCALLY';
// export const PIZZA_UPDATE_REMOTELY = 'PIZZA_UPDATE_REMOTELY';

export const PIZZA_CREATE_LOCALLY = 'PIZZA_CREATE_LOCALLY';
// export const PIZZA_CREATE_REMOTELY = 'PIZZA_CREATE_REMOTELY';